/**
 * Mapping from fingerprint API categories to spoofer setting paths.
 * Shared between fingerprint-monitor (inject) and message-handler (background).
 */
export const CATEGORY_TO_SETTING: Record<string, { category: string; setting: string }> = {
  'Canvas': { category: 'graphics', setting: 'canvas' },
  'OffscreenCanvas': { category: 'graphics', setting: 'offscreenCanvas' },
  'WebGL': { category: 'graphics', setting: 'webgl' },
  'WebGL Shaders': { category: 'graphics', setting: 'webglShaders' },
  'WebGPU': { category: 'graphics', setting: 'webgpu' },
  'DOMRect': { category: 'graphics', setting: 'domRect' },
  'TextMetrics': { category: 'graphics', setting: 'textMetrics' },
  'SVG': { category: 'graphics', setting: 'svg' },
  'Audio': { category: 'audio', setting: 'audioContext' },
  'Offline Audio': { category: 'audio', setting: 'offlineAudio' },
  'Audio Latency': { category: 'audio', setting: 'latency' },
  'Codecs': { category: 'audio', setting: 'codecs' },
  'Screen': { category: 'hardware', setting: 'screen' },
  'Screen Frame': { category: 'hardware', setting: 'screenFrame' },
  'Screen Orientation': { category: 'hardware', setting: 'orientation' },
  'Hardware': { category: 'hardware', setting: 'deviceMemory' },
  'Touch': { category: 'hardware', setting: 'touch' },
  'Sensors': { category: 'hardware', setting: 'sensors' },
  'Battery': { category: 'hardware', setting: 'battery' },
  'Media Devices': { category: 'hardware', setting: 'mediaDevices' },
  'Navigator': { category: 'navigator', setting: 'userAgent' },
  'Client Hints': { category: 'navigator', setting: 'clientHints' },
  'Clipboard': { category: 'navigator', setting: 'clipboard' },
  'Vibration': { category: 'navigator', setting: 'vibration' },
  'Timezone': { category: 'timezone', setting: 'intl' },
  'Fonts': { category: 'fonts', setting: 'enumeration' },
  'CSS Fonts': { category: 'fonts', setting: 'cssDetection' },
  'WebRTC': { category: 'network', setting: 'webrtc' },
  'Network': { category: 'network', setting: 'connection' },
  'Timing': { category: 'timing', setting: 'performance' },
  'CSS': { category: 'css', setting: 'mediaQueries' },
  'Speech': { category: 'speech', setting: 'synthesis' },
  'Permissions': { category: 'permissions', setting: 'query' },
  'Notification': { category: 'permissions', setting: 'notification' },
  'Storage': { category: 'storage', setting: 'estimate' },
  'IndexedDB': { category: 'storage', setting: 'indexedDB' },
  'WebSQL': { category: 'storage', setting: 'webSQL' },
  'Math': { category: 'math', setting: 'functions' },
  'Keyboard': { category: 'keyboard', setting: 'layout' },
  'Workers': { category: 'workers', setting: 'fingerprint' },
  'Errors': { category: 'errors', setting: 'stackTrace' },
  'Emoji': { category: 'rendering', setting: 'emoji' },
  'MathML': { category: 'rendering', setting: 'mathml' },
  'Intl': { category: 'intl', setting: 'apis' },
  'Crypto': { category: 'crypto', setting: 'webCrypto' },
  'Gamepad': { category: 'devices', setting: 'gamepad' },
  'MIDI': { category: 'devices', setting: 'midi' },
  'Bluetooth': { category: 'devices', setting: 'bluetooth' },
  'USB': { category: 'devices', setting: 'usb' },
  'Serial': { category: 'devices', setting: 'serial' },
  'HID': { category: 'devices', setting: 'hid' },
  'Features': { category: 'features', setting: 'detection' },
  'Apple Pay': { category: 'payment', setting: 'applePay' },
};
